### ISSUE TITLE
[Feature Request] Dialog for Multiple versions of Movie

### ISSUE THREAD

**Issue by starman2908** [kodi-connect/kodi-connect.github.io#1]
Hi Tomas,

So happy to see this skill working again . In my kodi database I have multiple instances of a movie geared for remote streaming depending on device/connection. So when I ask Alexa to play a something, kodi may come display a dialogue box to select and would have to use my remote control to choose and enter which version to playback.

Was wondering on the feasibility of this dialogue choice to be read back by Alexa met with a voice command for option. Something like :

'which version do you want to play? 1, [Reads dialogue Option 1], 2 [Reads dialogue Option 2].

Don't know if its possible on the video skill but thought i'd ask as you'll know better.

Thanks for your hard work on this truly amazing skill. I've made a small contribution for you to have a few (well deserved) drinks on me 👍

**Comment by tkislan** [comment]
I'm sorry, but Alexa Video skill interface is defined by Amazon, and I cannot implement any custom voice handling. I basically don't define any language/request models.
